### PR TITLE
Fix: block tiny url domain while creating tiny url

### LINKED ISSUE #131: block domain tiny.realdevsquad.com while creating a tiny link
### Issue Description

If try to create a tiny link for https://google.com/ it gives me a tiny url. Now with the received url if i try to create another tiny link it will give me another tiny link. I can do it n times(i tried it 4 5 times). 

More or less creating tiny urls for the tiny urls.

### Expected Behavior

If the received tiny url is sent again it should show that domain is blocked.

### Current Behavior

If the received tiny url is sent again it creates a link

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [x] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
1. [Step 1]
2. [Step 2]

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by fakhruddinkw**
## Issue Ticket Number

- Closes #131 

## Description

The config.Domain variable contains http scheme also in the string, because of which the tiny site domain is bypassing the check. After parsing the config.Domain, this should work

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment for dev to main._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.

## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: config/core-config.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ var (
 	JwtIssuer            string
 	AllowedOrigin        string
 	Port                 string
+	WebAppBaseDomain     string
```
Comment (prakashchoudhary07) [inline config/core-config.go:29]: This is a URL?

Comment (fakhruddinkw) [reply config/core-config.go:29]: yes, fixing the name. Thank you!

**Review by prakashchoudhary07 — APPROVED** [review]
