### PR TITLE
Fix db error

### LINKED ISSUE #83: Token Generation and Endpoint Issue in /self When Database is Down or No User Data Exists
### Issue Description

The current implementation allows token generation and endpoint /self access with data keys even when the database is down or no user data exists in the database. This behavior poses a security risk and inconsistency in the application's functionality

### Expected Behavior

- Token Generation: When the database is down or inaccessible, token generation should fail, and an appropriate error response should be returned.
- Endpoint /self: The /self endpoint should return an error response with empty object

### Current Behavior

- Token Generation: Even if the database is down or inaccessible, the application generates a token for the user.
- Endpoint /self: The /self endpoint returns data even if no user data exists in the database.

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [ ] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
1. [Step 1]
2. [Step 2]

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by vinit717**
## Issue Ticket Number

-   closes #83 

## Description

This PR addresses the security risk and inconsistency in the application's behavior by ensuring that token generation and endpoint /self operate correctly in all scenarios.

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment for dev to main._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.

## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: controllers/auth.go [hunk 1]
```diff
@@ -51,50 +51,70 @@ func GoogleLogin(ctx *gin.Context) {
...
+        })
+        return
+    }
+
+    if db == nil {
+        ctx.JSON(500, gin.H{
+            "message": "database is not available",
+        })
+        return
+    }
```
Comment (prakashchoudhary07) [inline controllers/auth.go:74]: Why is there here?

Comment (vinit717) [reply controllers/auth.go]: removed have a look

**Review by prakashchoudhary07 — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]
