### PR TITLE
Fix db issue while creating user(google-login)

### LINKED ISSUE #88: Google login issue when inserting new user
### Issue Description

When we login with google and user is new and we inserted on db we are getting error related to row

### Expected Behavior

[Describe what should happen when this issue is resolved.]

### Current Behavior

[Explain what currently happens when this issue is encountered.]

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [ ] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
1. [Step 1]
2. [Step 2]

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by vinit717**
## Issue Ticket Number

-   closes #88 

## Description

In this PR db issue of SQL row related is been resolved

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment for dev to main._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.

## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: controllers/auth.go [hunk 1]
```diff
@@ -55,56 +55,90 @@ func GoogleCallback(ctx *gin.Context, db *bun.DB) {
...
+    defer func() {
+        if p := recover(); p != nil {
+            tx.Rollback()
+            panic(p)
+        } else if err != nil {
+            tx.Rollback()
+        } else {
+            err = tx.Commit()
+        }
+    }()
```
Comment (prakashchoudhary07) [inline controllers/auth.go:85]: Are we doing this in a transaction?

Comment (vinit717) [reply controllers/auth.go:83]: We are managing the database operations within a transaction

**Review by prakashchoudhary07 — APPROVED** [review]
