### PR TITLE
Fix jwt generation and verification to include userid

### LINKED ISSUE #126: Add UserID to JWT Token and Refactor API Structure for User Authentication
### Issue Description

Currently, some APIs retrieve user data separately and send the `userID` in the body of the request. This approach is not ideal and adds unnecessary complexity to the authentication process. To improve security and streamline the flow, we need to include `userID` directly in the JWT token and refactor the API structure to extract the `userID` from the token instead of the request body.

### Expected Behavior

- `userID` should be included as a claim in the JWT token.
- APIs should extract `userID` from the JWT token instead of the request body.
- The `userID` should be an `int64` and passed around in a type-safe way, ensuring consistency across all API endpoints.
- The middleware should handle the extraction and validation of `userID` from the token.

### Current Behavior

- `userID` is currently retrieved separately from user data and sent in the body of the API requests.
- This approach is inefficient and prone to errors, as it relies on the correct `userID` being passed explicitly.
- Some APIs depend on user data being fetched and then manually added to the request body, which creates inconsistency and potential security risks.

### Screenshots

[Provide any screenshots or images if applicable.]

### Reproducibility

- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce
1. Call any API where user data is fetched separately and `userID` is sent in the body of the request.
2. Notice that `userID` is passed explicitly in the request body instead of being extracted from the JWT token.

### Severity/Priority
- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Additional Information

- Refactoring the API structure will involve changing the middleware to handle `userID` extraction from the JWT token.
- Changes will need to be propagated across all APIs that currently fetch and use `userID` separately in the request body.
- Testing will be required to ensure that the new token-based `userID` handling works consistently across the project.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by vinit717**
## Issue Ticket Number

-  closes #126 

## Description

Fixed the jwt generation and verification process by adding user-id to token so we extract user-id from cookie rather than from body on a request

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment for dev to main._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

https://github.com/user-attachments/assets/de37ab15-9a0c-4987-bffa-2954edea0279

## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: controllers/url.go [hunk 1]
```diff
@@ -76,7 +84,7 @@ func CreateTinyURL(ctx *gin.Context, db *bun.DB) {
 
 	count, err := db.NewSelect().
 		Model(&models.Tinyurl{}).
-		Where("user_id = ?", body.UserID).
+		Where("user_id = ?", userID).
```
Comment (iamitprakash) [inline controllers/url.go:87]: can't use AND syntax

File: controllers/url.go [hunk 2]
```diff
@@ -112,7 +125,7 @@ func CreateTinyURL(ctx *gin.Context, db *bun.DB) {
 
 	updatedCount, err := db.NewSelect().
 		Model(&models.Tinyurl{}).
-		Where("user_id = ?", body.UserID).
+		Where("user_id = ?", userID).
```
Comment (iamitprakash) [inline controllers/url.go:128]: same here

**Review by iamitprakash — CHANGES_REQUESTED** [review]

File: tests/unit/jwt_test.go [hunk 3]
```diff
@@ -36,32 +40,51 @@ func TestVerifyJWT(t *testing.T) {
...
-
+		claims, validTokenError := utils.VerifyToken(validToken)
 		if validTokenError != nil {
 			t.Fatalf("Error: %v", validTokenError)
 		}
 
-		if email != dummyUser.Email {
-			t.Fatalf("Expected %v but got %v", dummyUser.Email, email)
+		if claims["email"] != dummyUser.Email {
+			t.Fatalf("Expected email %v but got %v", dummyUser.Email, claims["email"])
```
Comment (iamitprakash) [inline tests/unit/jwt_test.go:57]: here

**Review by iamitprakash — APPROVED** [review]
